* se corrigen errores * se coloca una validacion de parametros

diff --git a/cocsign b/cocsign
--- a/cocsign
+++ b/cocsign
@@ -20,15 +20,25 @@ function check () {
 	fi
 }
 
+function parame () {
+	if ! [[ -z $2 ]]; then
+		echo -e "\e[00;31mERROR: Se insertaron Parametros innecesarios.\e[00m"
+		exit 1
+	fi
+}
+
 case "$1" in
 	instalar)
 		clear
+		parame
 		if [[ "$EUID" != "0" ]]; then
 			echo -e "\e[00;31mERROR: Debe ser root.\e[00m"
 			exit 1
 		fi
 		cp /etc/apt/sources.list /etc/apt/sources.list.old
-		echo -e "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse""\n""deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse""\n""deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" > /etc/apt/sources.list
+		echo "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" > /etc/apt/sources.list
+		echo "deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse" >> /etc/apt/sources.list
+		echo "deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" >> /etc/apt/sources.list
 		apt -q update
 		apt -qy install gnupg wget xclip beep
 		mv -f /etc/apt/sources.list.old /etc/apt/sources.list
@@ -37,6 +47,10 @@ case "$1" in
 
 	gpg)
 		check
+		if [[ -z $2 ]]; then
+			echo -e "\e[00;31mERROR: Faltan parametros.\e[00m"
+			exit 1
+		fi
 		echo -e "\e[00;1;92mRealizando limpieza\e[00m"
 		rm -f /tmp/genkey
 		rm -f /tmp/listo
@@ -117,6 +131,7 @@ case "$1" in
 
 	ssh)
 		check
+		parame
 		echo -e "\e[00;1;92mGenerando llave SSH\e[00m"
 		ssh-keygen -b 1024 -t rsa -f "$HOME"/.ssh/id_rsa -N ''
 		echo ""
