* se agrega una comprobacion del locale para verificar si se puede actualizar

diff --git a/cocsign b/cocsign
--- a/cocsign
+++ b/cocsign
@@ -4,6 +4,11 @@
 LC_ALL=C
 minombre="UbuntuCodeofConduct-2.0.txt"
 
+if [[ $(locale | grep LANG= | cut -c 6-16) = "es_VE.UTF-8" ]]; then
+	echo -e "\e[00;31mERROR: $(basename $0) no puede ejecutarse en este ordenador.\e[00m"
+	exit 1
+fi
+
 function pause() {
 	read -p "$*"
 }
